version: "3.9"

services:
  nodejs:
    tty: true
    container_name: nodejs_morpion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
    ports:
      - 8080:8080
